language: node_js
node_js:
  - "node"
install:
  - npm i -g npm@5.8.0
  - npm install
script:
  - npm run build:test
  - npm run build:pro
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.npm"